DROP TABLE IF EXISTS message_logs;

CREATE TABLE message_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  message_id VARCHAR(255),
  doctor_id INT,
  doctor_name VARCHAR(255),
  doctor_phone VARCHAR(20),
  doctor_birthday DATE,
  doctor_anniversary DATE,
  doctor_clinic_anniversary DATE,
  doctor_clinic_name VARCHAR(255),
  message_type ENUM('birthday', 'anniversary', 'clinic_anniversary'),
  template_name VARCHAR(255),
  recipient_id VARCHAR(20),
  status ENUM('sent', 'delivered', 'read', 'failed'),
  retry_count TINYINT DEFAULT 0,
  billable TINYINT(1),
  category VARCHAR(100),
  timestamp VARCHAR(20),
  error_code INT,
  error_title VARCHAR(255),
  error_message TEXT,
  error_details TEXT,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  INDEX idx_recipient (recipient_id),
  INDEX idx_status (status),
  INDEX idx_message_type (message_type),
  INDEX idx_doctor_id (doctor_id),
  CONSTRAINT fk_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE SET NULL ON UPDATE CASCADE
);
