location /videos/download/ {
    alias /home/alembicdigilabs/Projects/videos/;

    types {
        video/mp4  mp4;
    }
    default_type video/mp4;

    add_header Accept-Ranges bytes;
    add_header Cache-Control "public, max-age=86400";
    add_header Access-Control-Allow-Origin "*";

    autoindex off;
}


location /videos/download/ {
        # The physical path to your folder
        alias /home/alembicdigilabs/Projects/videos/;

        # Ensure correct MIME type for MP4
        default_type video/mp4;

        # Optional: Allow you to see a list of files in the browser for testing
        # Turn this 'off' in production for security
        autoindex on;
}
